trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: dependencies
    displayName: "Install dependencies"
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '22.x'
   



